apiVersion: v1
kind: Service
metadata:
  name: group4-mysql
  namespace: group-4
spec:
  ports:
    - protocol: TCP
      port: 3306
      name: mysql
      targetPort: 3306
  selector:
    app: mysql