apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: group4-mysql
  namespace: group-4
spec:
  serviceName: "group4-mysql"
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8.2.0
          env:
            - name: MYSQL_DATABASE
              value: stockdb
            - name: MYSQL_ROOT_PASSWORD
              value: pass
            - name: MYSQL_USER
              value: user
            - name: MYSQL_PASSWORD
              value: user
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-data
          persistentVolumeClaim:
            claimName: shobteeprajump-mysql-pvc-a
        

          


