apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shobteeprajump-mysql-pvc-a
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi
  volumeName: shobteeprajump-mysql-pv-a
  storageClassName: shobteeprajump-storage-a
