version: '3'

services:
  backend:
    build: .
    ports:
      - "8000:8000"
    networks:
      - grafanet
    depends_on:
      - mysql
    environment:
      - DB_HOST=mysql
      - DB_USER=user
      - DB_PASSWORD=user
      - DB_NAME=stockdb

  mysql:
    image: mysql:8.2.0
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-init:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_DATABASE=stockdb
      - MYSQL_ROOT_PASSWORD=pass
      - MYSQL_USER=user
      - MYSQL_PASSWORD=user
  