apiVersion: v1
kind: Service
metadata:
  labels:
    app: shobteeprajump-obs
  name: shobteeprajump-obs-svc
  namespace: group-4-obs
spec:
  ports:
  - name: grafana-agent-traces-otlp-grpc
    port: 4317
    protocol: TCP
    targetPort: 4317
  - name: grafana-agent-traces-otlp-http
    port: 4318
    protocol: TCP
    targetPort: 4318
  - name: grafana-agent-dashbaord
    port: 12345
    protocol: TCP
    targetPort: 12345
  selector:
    app: shobteeprajump-obs
  type: ClusterIP

