apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  creationTimestamp: null
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
  name: shobteeprajump-ingress
spec:
  ingressClassName: nginx
  rules:
  - host: tcc-01.th1.proen.cloud
    http:
      paths:
      - backend:
          service:
            name: shobteeprajump-client-service
            port:
              number: 3002
        path: /group-4/client
        pathType: Prefix
status:
  loadBalancer: {}
