apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shobteeprajump-rabbitmq-pvc
  namespace: group-4
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi
  volumeName: shobteeprajump-rabbitmq-pv
  storageClassName: shobteeprajump-storage-b
