---
apiVersion: v1
kind: Service
metadata:
  name: group4-rabbitmq
spec:
  ports:
    - protocol: TCP
      port: 5672
      name: rabbitmq
      targetPort: 5672
    - protocol: TCP
      port: 15672
      name: rabbitmq-management
      targetPort: 15672
  selector:
    app: rabbitmq