apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: group4-rabbitmq
  namespace: group-4
spec:
  serviceName: "group4-rabbitmq"
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:3.12
          ports:
            - containerPort: 5672
            - containerPort: 15672
          volumeMounts:
            - name: rabbitmq-data
              mountPath: /var/lib/rabbitmq/mnesia
      volumes:
        - name: rabbitmq-data
          persistentVolumeClaim:
            claimName: shobteeprajump-rabbitmq-pvc

