apiVersion: v1
kind: PersistentVolume
metadata:
  name: shobteeprajump-rabbitmq2-pv
  labels:
    type: local
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /opt/app/group-4-shobteeprajump/rabbitmq2
  persistentVolumeReclaimPolicy: Retain
  storageClassName: shobteeprajump-storage-c
