run-name: Bump Version, Build Docker image then Push to registry
name: Build Docker image the Push to registry
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    # outputs:
    #   image_tag: ${{ steps.meta.outputs.tags }}
    # environment: dev
    steps:
      - uses: actions/checkout@v2
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.TOD_TOKEN }}
      # - name: Login to Docker Hub
      #   uses: docker/login-action@v3
      #   with:
      #     username: ${{ secrets.TOD_DOCKER_USERNAME }}
      #     password: ${{ secrets.TOD_DOCKERHUB_TOKEN }}
      # - name: get tag name
      #   uses: little-core-labs/get-git-tag@v3.0.1
      #   id: tagName
      #   with:
      #     tagRegex: "v"
      - name: Test get tag
        run: |
            echo "1 - ${{ GITHUB.REF }}"
            echo "2 - ${{ steps.tag_version.outputs.new_tag }}"
      # - name: Build and push
      #   uses: docker/build-push-action@v5
      #   with:
      #     push: true
      #     tags: justtod/shobteeprajump:latest
      # - name: Build and push Docker image
      #   id: build-and-push
      #   uses: docker/build-push-action@0565240e2d4ab88bba5387d719585280857ece09 # v5.0.0
      #   with:
      #     context: .
      #     push: true
      #     tags: ${{ steps.meta.outputs.tags }}
      #     labels: ${{ steps.meta.outputs.labels }}
